### PR TITLE
Update SemanticCompoundQueries.php

### PR DESCRIPTION
**Pull request by kghbln**
Globalize for Composer

Refs #22

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
"Globalize" :)

**Comment by kghbln** [comment]
> "Globalize" :)

@JeroenDeDauw Indeed, think global, act local. I believe that we should now get this out the the public since the extension is currently not loading. I guess it is more a 1.0.1 than an 1.1.0. What do you think.

**Comment by JeroenDeDauw** [comment]
1.0.1

**Comment by kghbln** [comment]
Here we are: https://github.com/SemanticMediaWiki/SemanticCompoundQueries/pull/24

**Pull request merged**
