### PR TITLE
 Remove I18n shim

### PR DESCRIPTION
**Pull request by kghbln**
Refs issue https://github.com/SemanticMediaWiki/SemanticCompoundQueries/issues/11

### CODE REVIEW

**Comment by mwjames** [comment]
Failures as per https://github.com/SemanticMediaWiki/SemanticCompoundQueries/pull/10#issuecomment-230366365.

**Comment by mwjames** [comment]
https://github.com/SemanticMediaWiki/SemanticInterlanguageLinks/blob/master/tests/phpunit/Integration/I18nJsonFileIntegrityTest.php should be added.

**Comment by kghbln** [comment]
> should be added.

Will do assuming that it is just a mere imitation. :)

**Comment by kghbln** [comment]
> should be added.

@mwjames Hopefully it is cool.

**Comment by PeterTheOne** [comment]
Looks like your test passes. With #9 merged, this should be green.

**Pull request merged**
