### PR TITLE
fix queryAndMergeResults return values

### PR DESCRIPTION
**Pull request by PeterTheOne**
@yaronkoren This change did not make it into your commits: https://github.com/wikimedia/mediawiki-extensions-SemanticCompoundQueries/pull/1/files#diff-b24b89d16098451f1fc1a80b15193751L87.

Old PR: https://github.com/wikimedia/mediawiki-extensions-SemanticCompoundQueries/pull/3

### CODE REVIEW

**Comment by PeterTheOne** [comment]
Btw. without this change the API is in a broken state.. ;)

**Comment by yaronkoren** [comment]
@PeterTheOne - sorry about that! I kept meaning to make the change, but then it kept slipping my mind. I can make the change now, but now I'm not sure whether to do it here, or on wikimedia.org... which is the master version now? Or will either one work?

**Comment by PeterTheOne** [comment]
As far as I understood this is the master version now.. @JeroenDeDauw?

**Comment by JeroenDeDauw** [comment]
Here. I will update the wmf repo by replacing the files there with a readme that links here, to avoid confusion.

**Comment by JeroenDeDauw** [comment]
Merging here as @yaronkoren seems to be OK with the PR

**Pull request merged**
