### PR TITLE
Rename group for consistency

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: https://doc.semantic-mediawiki.org/group__SemanticCompoundQueries.html

This PR addresses or contains:
-  Renames the group defined for this extension to match its name

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by JeroenDeDauw** [comment]
If this group is used then the uses should also be updated. If it is not used then it can be deleted.

Looks like it is not used

**Comment by kghbln** [comment]
What I would like to do is get some consistency into the display of modules as listed here: https://doc.semantic-mediawiki.org/modules.html

> Looks like it is not used

Something is using it: https://doc.semantic-mediawiki.org/modules.html

**Comment by JeroenDeDauw** [comment]
I don't see anything using it: https://doc.semantic-mediawiki.org/group__SemanticCompoundQueries.html

**Comment by kghbln** [comment]
Same for all other extensions meaning we need 11 pulls instead of just this one. One the other hand we would get another link to the extension. :)

**Pull request closed without merging**
